# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def shared_pods
  # Social
#  pod 'TwitterKit'
  
  # Networking
  pod 'Moya/RxSwift', '~> 11.0'

  # Data'
  pod 'ObjectMapper'

  # Utility
  pod 'R.swift'

  # UI Helper
  pod 'IQKeyboardManagerSwift'
  
  # Redux
  pod 'ReSwift'
  pod 'ReSwiftRouter'
  pod 'ReRxSwift', '~> 1.0'
  
  # Reactive
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
end


target 'daw-purchases' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for daw-purchases
  shared_pods


  target 'daw-purchasesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'daw-purchasesUITests' do
    # Pods for testing
  end

end
