# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def shared_pods
  # Social
#  pod 'TwitterKit'
  
  # Networking
  pod 'Moya/RxSwift', '14.0.0'
  pod 'Result', '5.0.0'

  # Data'
  pod 'ObjectMapper', '4.2.0'

  # Utility
  pod 'R.swift', '5.2.2'

  # UI Helper
  pod 'IQKeyboardManagerSwift', '6.5.6'
  
  # Redux
  pod 'ReSwift', '5.0.0'
  pod 'ReSwiftRouter', '~>0.7.1'
  pod 'ReRxSwift', '2.2.2'
  
  # Reactive
  pod 'RxSwift', '5.1.1'
  pod 'RxCocoa', '5.1.1'
  

end


target 'daw-purchases' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for daw-purchases
  shared_pods


  target 'daw-purchasesTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '5.1.1'
    pod 'RxTest', '5.1.1'
  end

  target 'daw-purchasesUITests' do
    # Pods for testing
  end

end
